
- input_type: log
  paths:
  {%- for path in paths %}
   - {{path}}
  {%- endfor %}
  exclude_files: [".gz$"]
  fields:
    source_type: bro-netcontrol_catch_release
    pipeline_id: {{beat.pipeline_id}}